### ISSUE TITLE
incorrect focal center when used under a nested component

### ISSUE THREAD

**Issue by ctf0** [EvodiaAut/vue-focuspoint-component#2]
when testing the component directly the focal is placed correctly & the css `calc` is right, 
however when using the focus-point component under another component the focal is no longer in check as below

![test](https://user-images.githubusercontent.com/7388088/67584613-5493e880-f74e-11e9-8c65-8855aac8f40e.jpg)

ps: i've changed the css to make it more visible but it shouldn't affect the end result, or maybe am missing something 🤔

**Comment by EvodiaAut** [comment]
Hey @ctf0,

i'm sorry for my late feedback.
Can you rebuild the online where then I would do easier?

**Comment by ctf0** [comment]
i've found the issue, i was using `v-show` on the nested component which renders the focus point component too soon & therefor it cant calculate correctly the position of the cursor.

using `v-if` solves this issue, sorry for the inconvenience

**Comment by EvodiaAut** [comment]
No problem, always glad to
